// Auto-generated by: bun run generate-types
// Do not edit manually. Run `bun run generate-types` to regenerate.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      reports: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          reporter_id: string | null
          status: 'queued' | 'transcribing' | 'processing' | 'ready' | 'spam' | 'quarantine' | 'archived' | 'actioned'
          text_description: string | null
          transcript: string | null
          location: string | null
          business_name: string | null
          category: 'taxi_scam' | 'fake_exchange' | 'online_fraud' | 'restaurant_scam' | 'other' | null
          urgency_score: number | null
          urgency_reason: string | null
          cluster_id: string | null
          entities: Json | null
          pipeline_started_at: string | null
          pipeline_completed_at: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          reporter_id?: string | null
          status?: 'queued' | 'transcribing' | 'processing' | 'ready' | 'spam' | 'quarantine' | 'archived' | 'actioned'
          text_description?: string | null
          transcript?: string | null
          location?: string | null
          business_name?: string | null
          category?: 'taxi_scam' | 'fake_exchange' | 'online_fraud' | 'restaurant_scam' | 'other' | null
          urgency_score?: number | null
          urgency_reason?: string | null
          cluster_id?: string | null
          entities?: Json | null
          pipeline_started_at?: string | null
          pipeline_completed_at?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          reporter_id?: string | null
          status?: 'queued' | 'transcribing' | 'processing' | 'ready' | 'spam' | 'quarantine' | 'archived' | 'actioned'
          text_description?: string | null
          transcript?: string | null
          location?: string | null
          business_name?: string | null
          category?: 'taxi_scam' | 'fake_exchange' | 'online_fraud' | 'restaurant_scam' | 'other' | null
          urgency_score?: number | null
          urgency_reason?: string | null
          cluster_id?: string | null
          entities?: Json | null
          pipeline_started_at?: string | null
          pipeline_completed_at?: string | null
        }
        Relationships: []
      }
      report_media: {
        Row: {
          id: string
          report_id: string
          storage_path: string
          kind: 'image' | 'video' | 'audio'
          mime_type: string
          size_bytes: number | null
          created_at: string
        }
        Insert: {
          id?: string
          report_id: string
          storage_path: string
          kind: 'image' | 'video' | 'audio'
          mime_type: string
          size_bytes?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          report_id?: string
          storage_path?: string
          kind?: 'image' | 'video' | 'audio'
          mime_type?: string
          size_bytes?: number | null
          created_at?: string
        }
        Relationships: [
          { foreignKeyName: 'report_media_report_id_fkey'; columns: ['report_id']; referencedRelation: 'reports'; referencedColumns: ['id'] }
        ]
      }
      pipeline_runs: {
        Row: {
          id: string
          report_id: string
          step: 'whisper' | 'spam' | 'dedupe' | 'category' | 'urgency' | 'entities' | 'web_research'
          status: 'pending' | 'running' | 'done' | 'failed' | 'skipped'
          result: Json | null
          attempts: number
          started_at: string | null
          finished_at: string | null
          error: string | null
        }
        Insert: {
          id?: string
          report_id: string
          step: 'whisper' | 'spam' | 'dedupe' | 'category' | 'urgency' | 'entities' | 'web_research'
          status?: 'pending' | 'running' | 'done' | 'failed' | 'skipped'
          result?: Json | null
          attempts?: number
          started_at?: string | null
          finished_at?: string | null
          error?: string | null
        }
        Update: {
          id?: string
          report_id?: string
          step?: 'whisper' | 'spam' | 'dedupe' | 'category' | 'urgency' | 'entities' | 'web_research'
          status?: 'pending' | 'running' | 'done' | 'failed' | 'skipped'
          result?: Json | null
          attempts?: number
          started_at?: string | null
          finished_at?: string | null
          error?: string | null
        }
        Relationships: [
          { foreignKeyName: 'pipeline_runs_report_id_fkey'; columns: ['report_id']; referencedRelation: 'reports'; referencedColumns: ['id'] }
        ]
      }
      report_clusters: {
        Row: {
          id: string
          canonical_report_id: string
          report_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          canonical_report_id: string
          report_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          canonical_report_id?: string
          report_count?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      report_embeddings: {
        Row: {
          report_id: string
          embedding: number[]
          created_at: string
        }
        Insert: {
          report_id: string
          embedding: number[]
          created_at?: string
        }
        Update: {
          report_id?: string
          embedding?: number[]
          created_at?: string
        }
        Relationships: []
      }
      evidence: {
        Row: {
          id: string
          report_id: string
          source_url: string
          title: string | null
          snippet: string | null
          relevance_score: number | null
          fetched_at: string
        }
        Insert: {
          id?: string
          report_id: string
          source_url: string
          title?: string | null
          snippet?: string | null
          relevance_score?: number | null
          fetched_at?: string
        }
        Update: {
          id?: string
          report_id?: string
          source_url?: string
          title?: string | null
          snippet?: string | null
          relevance_score?: number | null
          fetched_at?: string
        }
        Relationships: []
      }
      categories: {
        Row: { id: string; label_cs: string; label_en: string }
        Insert: { id: string; label_cs: string; label_en: string }
        Update: { id?: string; label_cs?: string; label_en?: string }
        Relationships: []
      }
      audit_log: {
        Row: {
          id: string
          created_at: string
          user_id: string | null
          action: string
          target_id: string | null
          meta: Json | null
        }
        Insert: {
          id?: string
          created_at?: string
          user_id?: string | null
          action: string
          target_id?: string | null
          meta?: Json | null
        }
        Update: {
          id?: string
          created_at?: string
          user_id?: string | null
          action?: string
          target_id?: string | null
          meta?: Json | null
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      match_reports: {
        Args: {
          query_embedding: number[]
          match_threshold: number
          match_count: number
        }
        Returns: Array<{ report_id: string; similarity: number }>
      }
      increment_cluster_count: {
        Args: { cluster_id: string }
        Returns: undefined
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
